# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'ProductivityApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductivityApp

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'IQKeyboardManagerSwift'


end
